apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: hello-kubernetes-request-auth
spec:
  selector:
    matchLabels:
      app: hello-kubernetes
  jwtRules:
  - issuer: "https://sts.windows.net/${_tenantId}/"
    audiences:
      - https://${_appUrl}
    jwksUri: "https://login.microsoftonline.com/${_tenantId}/discovery/keys"
